### ISSUE TITLE
输入中文会闪退、清空内容。输入英文则没有问题。

### ISSUE THREAD

**Issue by william2113** [dicarne/sy-secret-block#3]
中文拼音输入会闪退、清空内容。英文输入则没有问题。

**Comment by dicarne** [comment]
研究了一下，貌似不是我的问题。思源修改了块选中机制，不清楚为什么通过输入法选字以后会自动选中整个块，这就会导致后续的文字错误的替换了整个块的内容。
块仍然是挂件块，但内容却错误的变成了文字，于是导致思源报错了，整个块就不能显示了。
不清楚怎么样才能不让它自动选中，这可能要联系原作者，内部的挂件是不能实现选中块的。
（另外，新的选中机制真的很蠢，只要选择全部文字就自动选中整个块，就会错误的删除整个挂件，离谱）

**Comment by dicarne** [comment]
临时的解决办法：第一个字符不要是中文，用空格什么的就行。后面可以正常输入中文。

**Comment by dicarne** [comment]
https://ld246.com/article/1644827326901
论坛提了这个问题，不知道什么时候修

**Comment by dicarne** [comment]
https://github.com/siyuan-note/siyuan/issues/4072

**Comment by tcmtom** [comment]
这个问题现在好像已经解决了

**Comment by dicarne** [comment]
经验证，思源笔记1.8.7已经解决此问题
