### ISSUE TITLE
你好，反映一个在不同设备创建挂件因为IP不同不能使用的问题

### ISSUE THREAD

**Issue by ifknt** [dicarne/sy-secret-block#5]
1、在 A 电脑端思源创建挂件，此时挂件IP开头是127.0.0.1，思源笔记开启伺服；

2、同一局域网中，A 电脑在局域网IP是192.168.1.2。用 B 电脑网页访问 A 电脑 创建挂件的文档，挂件块中会提示127.0.0.1拒绝链接请求，A电脑网页中访问该文档则正常显示；

3、此时在 B 电脑浏览器中新建文档并创建挂件，挂件IP是192.168.1.X开头，B电脑可以正常显示挂件，但在 A电脑中会显示拒绝请求；

可以麻烦修复下这个问题么？

**Comment by dicarne** [comment]
不好意思这个我可能改不了。开发挂件是不管理也不能管理ip的，这是思源笔记内部实现是这样。以后可能会改，但不知道什么时候，建议去论坛找D大反馈。我看了，别的笔记API ip都是正确的，就挂件写死了127.0.0.1

**Comment by dicarne** [comment]
2.1.14版本经测试，通过挂件选项添加挂件，可以正常在其他网络访问。
