### ISSUE TITLE
同一文档中，相同密码的加密块（该挂件）一个解锁全都解锁

### ISSUE THREAD

**Issue by EberhardLin** [dicarne/sy-secret-block#7]
使用中发现，一个文档中包含了三个密码相同的加密块，但只要其中一个加密块被解锁了，所有加密块都会被解锁。
各个加密块更换了不同的密码之后，其他加密块会不断出现“密码错误”的提示，如图所示：
![image](https://user-images.githubusercontent.com/98400319/175906883-11a987e3-3288-4f53-8874-9b389f47acb6.png)
目前有解决方案吗？

**Comment by dicarne** [comment]
密码相同解锁是feature，
错误提示太多是bug

**Comment by dicarne** [comment]
https://github.com/siyuan-note/bazaar/pull/745
新的版本应该可以解决错误过多的问题。另外，我在下拉菜单中增加一个选择是否批量解锁的功能，关闭后，就只会解锁当前块。
