### ISSUE TITLE
调整大小后内容丢失

### ISSUE THREAD

**Issue by joetin** [dicarne/sy-secret-block#8]
设定密码，输入内容，立即锁定，
再解锁，没有任何问题。
但是这时我又拖动了下右下角调整大小，然后再解锁，内容就空了。

经过测试，
在解锁状态下，调节大小就没有影响。
在锁定状态下，调节大小就会清空内容。

**Comment by dicarne** [comment]
研究了一下，感觉不是我的问题，改变挂件大小后，所有自定义属性都消失……

**Comment by dicarne** [comment]
https://github.com/siyuan-note/siyuan/issues/4885
这是一个老bug，我没有办法。在拖拽大小后，api会返回旧版本的数据。

**Comment by dicarne** [comment]
升级思源到2.1.14，该问题已修复，在我这测试没有问题。
